CREATE DATABASE CSHARPASSIGNMENT_DB;
USE CSHARPASSIGNMENT_DB;
CREATE TABLE CUSTOMER
(
	CustomerCode NVARCHAR(10)
	PRIMARY KEY,
	FirstName NVARCHAR(25) NOT NULL,
	LastName NVARCHAR(25) NOT NULL
)

CREATE TABLE INVOICE
(
	InvoiceDate DATETIME NOT NULL,
	InvoiceNo INTEGER IDENTITY(10000,1) NOT NULL,
	CustomerCode NVARCHAR(10) REFERENCES CUSTOMER(CustomerCode),
	Amount DECIMAL NOT NULL CHECK(Amount<=20000)
)

CREATE TABLE ARCHIVEDINVOICE
(
	InvoiceDate DATETIME NOT NULL,
	InvoiceNo INTEGER NOT NULL,
	CustomerCode NVARCHAR(10) REFERENCES CUSTOMER(CustomerCode),
	Amount DECIMAL NOT NULL CHECK(Amount<=20000)
)

DROP DATABASE CSHARPASSIGNMENT_DB;
DELETE FROM CUSTOMER;
SELECT * FROM CUSTOMER;
SELECT * FROM INVOICE;

CREATE PROCEDURE SP_MOVETOARCHIVED
@InvoiceNo int
AS
BEGIN

END
SELECT * FROM INVOICE WHERE SUBSTRING(CUSTOMERCODE,1,2)='SV'